spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lxqtpr2021
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        format_sql: true
        use_sql_comments: true
        highlight_sql: true


server:
  port: 8000