spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/account
    username: account
    password: account
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8084