version: '3'

networks:
  banking-system:
    driver: bridge

services:

  #############################################################################
  ###### Data Bases ###########################################################
  #############################################################################

  postgres-customer:
    container_name: customer-db
    image: postgres:latest
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
    ports:
      - "5435:5432"
    volumes:
      - ./volumes/customer:/data/postgres

  postgres-debit-card:
    container_name: debit-card-db
    image: postgres:latest
    environment:
      POSTGRES_DB: debit-card
      POSTGRES_USER: debit-card
      POSTGRES_PASSWORD: debit-card
    ports:
      - "5436:5432"
    volumes:
      - ./volumes/debit-card:/data/postgres

  postgres-account:
    container_name: account-db
    image: postgres:latest
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: account
      POSTGRES_PASSWORD: account
    ports:
      - "5437:5432"
    volumes:
      - ./volumes/account:/data/postgres
