services:
  postgres:
    image: postgres
    restart: always
    container_name: transactions-service-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lxqtpr2021
    volumes:
      - db-data:/postgres

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lxqtpr@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lxqtpr2021
    ports:
      - "5050:80"
    volumes:
      - pgAdmin-data:/pgadmin

volumes:
  db-data:
  pgAdmin-data: