spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/debit-card
    username: debit-card
    password: debit-card
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8083