spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/customer
    username: customer
    password: customer
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8082