spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
    org.springframework.security: DEBUG
server:
  port: 8762
  forward-headers-strategy: framework