spring:
  cloud:
    gateway:
      routes:
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/api/transactions/**

server:
  port: 8762

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO